baseurl = "http://oncodesign.io/"
languageCode = "en-us"
title = "On Code & Design"
theme = "hugo-lithium-theme"
googleAnalytics = "UA-80349200-1"
disqusShortname = "oncodesign"

[permalinks]
    post = "/:year/:month/:day/:filename/"
    page = "/:title/"

[params]
    description = "An anarchist's thoughts on code, design, and everything else"

[params.logo]
    url = "avatar.png"
    width = 50
    height = 50
